/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package child.hood.puzzle;

import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        one = new javax.swing.JButton();
        blank = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        ten = new javax.swing.JButton();
        eleven = new javax.swing.JButton();
        dis = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ok = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Puzzle Game");

        one.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        one.setText("11");
        one.setFocusable(false);
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        blank.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        blank.setFocusable(false);
        blank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blankActionPerformed(evt);
            }
        });

        two.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        two.setText("9");
        two.setFocusable(false);
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        three.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        three.setText("10");
        three.setFocusable(false);
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        four.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        four.setText("6");
        four.setFocusable(false);
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        five.setText("3");
        five.setFocusable(false);
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        six.setText("5");
        six.setFocusable(false);
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        seven.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        seven.setText("1");
        seven.setFocusable(false);
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        eight.setText("8");
        eight.setFocusable(false);
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        nine.setText("2");
        nine.setFocusable(false);
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        ten.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ten.setText("7");
        ten.setFocusable(false);
        ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenActionPerformed(evt);
            }
        });

        eleven.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        eleven.setText("4");
        eleven.setFocusable(false);
        eleven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(blank, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eleven, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blank, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eleven, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dis.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        dis.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Total Move : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Reset Puzzle");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Solve Like This");

        ok.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ok.setForeground(new java.awt.Color(0, 0, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ok.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ff.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(dis, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(440, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(240, 240, 240)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(dis, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel7)))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(266, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(30, 30, 30)))
        );

        jMenu1.setText("About");

        jMenuItem2.setText("About Developer");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private static int totalmove;
    
//public static 

public boolean chk(){
    
   return (blank.getText().toString().equals("")&&
           one.getText().toString().equals("1")&&
           two.getText().toString().equals("2")&&
           three.getText().toString().equals("3")&&
           four.getText().toString().equals("4")&&
           five.getText().toString().equals("5")&&
           six.getText().toString().equals("6")&&
           seven.getText().toString().equals("7")&&
           eight.getText().toString().equals("8")&&
           nine.getText().toString().equals("9")&&
           ten.getText().toString().equals("10")&&
           eleven.getText().toString().equals("11")
           );
    }
    private void blankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blankActionPerformed
        // TODO add your handling code here:
        totalmove++;
       String tmp = blank.getText().toString().trim();
       if(one.getText().toString().equals("")){
    one.setText(tmp);
    }
    else if(two.getText().toString().equals("")){
    two.setText(tmp);
    }
    else if(three.getText().toString().equals("")){
    three.setText(tmp);
    }
    else if(four.getText().toString().equals("")){
    four.setText(tmp);
    }
    else if(five.getText().toString().equals("")){
    five.setText(tmp);
    }
    else if(six.getText().toString().equals("")){
    six.setText(tmp);
    }
    else if(seven.getText().toString().equals("")){
    seven.setText(tmp);
    }
    else if(eight.getText().toString().equals("")){
    eight.setText(tmp);
    }
    else if(nine.getText().toString().equals("")){
    nine.setText(tmp);
    }
    else if(ten.getText().toString().equals("")){
    ten.setText(tmp);
    }
    else if(eleven.getText().toString().equals("")){
    eleven.setText(tmp);
    }
    else{}
    blank.setText("");
        dis.setText(totalmove+"");
        
        if(chk()){
        
          JOptionPane.showMessageDialog(NewJFrame.this,"You Solved The Puzzle");
              
        }
    }//GEN-LAST:event_blankActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
         totalmove++;
               String tmp = one.getText().toString().trim();
       if(blank.getText().toString().equals("")){
    blank.setText(tmp);
    }
    else if(two.getText().toString().equals("")){
    two.setText(tmp);
    }
    else if(three.getText().toString().equals("")){
    three.setText(tmp);
    }
    else if(four.getText().toString().equals("")){
    four.setText(tmp);
    }
    else if(five.getText().toString().equals("")){
    five.setText(tmp);
    }
    else if(six.getText().toString().equals("")){
    six.setText(tmp);
    }
    else if(seven.getText().toString().equals("")){
    seven.setText(tmp);
    }
    else if(eight.getText().toString().equals("")){
    eight.setText(tmp);
    }
    else if(nine.getText().toString().equals("")){
    nine.setText(tmp);
    }
    else if(ten.getText().toString().equals("")){
    ten.setText(tmp);
    }
    else if(eleven.getText().toString().equals("")){
    eleven.setText(tmp);
    }
    else{}
    one.setText("");
    dis.setText(totalmove+"");
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
         totalmove++;
               String tmp = two.getText().toString().trim();
       if(one.getText().toString().equals("")){
    one.setText(tmp);
    }
    else if(blank.getText().toString().equals("")){
    blank.setText(tmp);
    }
    else if(three.getText().toString().equals("")){
    three.setText(tmp);
    }
    else if(four.getText().toString().equals("")){
    four.setText(tmp);
    }
    else if(five.getText().toString().equals("")){
    five.setText(tmp);
    }
    else if(six.getText().toString().equals("")){
    six.setText(tmp);
    }
    else if(seven.getText().toString().equals("")){
    seven.setText(tmp);
    }
    else if(eight.getText().toString().equals("")){
    eight.setText(tmp);
    }
    else if(nine.getText().toString().equals("")){
    nine.setText(tmp);
    }
    else if(ten.getText().toString().equals("")){
    ten.setText(tmp);
    }
    else if(eleven.getText().toString().equals("")){
    eleven.setText(tmp);
    }
    else{}
    two.setText("");
        dis.setText(totalmove+"");
        
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
         totalmove++;
               String tmp = three.getText().toString().trim();
       if(one.getText().toString().equals("")){
    one.setText(tmp);
    }
    else if(two.getText().toString().equals("")){
    two.setText(tmp);
    }
    else if(blank.getText().toString().equals("")){
    blank.setText(tmp);
    }
    else if(four.getText().toString().equals("")){
    four.setText(tmp);
    }
    else if(five.getText().toString().equals("")){
    five.setText(tmp);
    }
    else if(six.getText().toString().equals("")){
    six.setText(tmp);
    }
    else if(seven.getText().toString().equals("")){
    seven.setText(tmp);
    }
    else if(eight.getText().toString().equals("")){
    eight.setText(tmp);
    }
    else if(nine.getText().toString().equals("")){
    nine.setText(tmp);
    }
    else if(ten.getText().toString().equals("")){
    ten.setText(tmp);
    }
    else if(eleven.getText().toString().equals("")){
    eleven.setText(tmp);
    }
    else{}
    three.setText("");
    dis.setText(totalmove+"");
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
         totalmove++;
               String tmp = four.getText().toString().trim();
       if(one.getText().toString().equals("")){
    one.setText(tmp);
    }
    else if(two.getText().toString().equals("")){
    two.setText(tmp);
    }
    else if(three.getText().toString().equals("")){
    three.setText(tmp);
    }
    else if(blank.getText().toString().equals("")){
    blank.setText(tmp);
    }
    else if(five.getText().toString().equals("")){
    five.setText(tmp);
    }
    else if(six.getText().toString().equals("")){
    six.setText(tmp);
    }
    else if(seven.getText().toString().equals("")){
    seven.setText(tmp);
    }
    else if(eight.getText().toString().equals("")){
    eight.setText(tmp);
    }
    else if(nine.getText().toString().equals("")){
    nine.setText(tmp);
    }
    else if(ten.getText().toString().equals("")){
    ten.setText(tmp);
    }
    else if(eleven.getText().toString().equals("")){
    eleven.setText(tmp);
    }
    else{}
    four.setText("");
    dis.setText(totalmove+"");
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
         totalmove++;
               String tmp = five.getText().toString().trim();
       if(one.getText().toString().equals("")){
    one.setText(tmp);
    }
    else if(two.getText().toString().equals("")){
    two.setText(tmp);
    }
    else if(three.getText().toString().equals("")){
    three.setText(tmp);
    }
    else if(four.getText().toString().equals("")){
    four.setText(tmp);
    }
    else if(blank.getText().toString().equals("")){
    blank.setText(tmp);
    }
    else if(six.getText().toString().equals("")){
    six.setText(tmp);
    }
    else if(seven.getText().toString().equals("")){
    seven.setText(tmp);
    }
    else if(eight.getText().toString().equals("")){
    eight.setText(tmp);
    }
    else if(nine.getText().toString().equals("")){
    nine.setText(tmp);
    }
    else if(ten.getText().toString().equals("")){
    ten.setText(tmp);
    }
    else if(eleven.getText().toString().equals("")){
    eleven.setText(tmp);
    }
    else{}
    five.setText("");
    dis.setText(totalmove+"");
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
         totalmove++;
               String tmp = six.getText().toString().trim();
       if(one.getText().toString().equals("")){
    one.setText(tmp);
    }
    else if(two.getText().toString().equals("")){
    two.setText(tmp);
    }
    else if(three.getText().toString().equals("")){
    three.setText(tmp);
    }
    else if(four.getText().toString().equals("")){
    four.setText(tmp);
    }
    else if(five.getText().toString().equals("")){
    five.setText(tmp);
    }
    else if(blank.getText().toString().equals("")){
    blank.setText(tmp);
    }
    else if(seven.getText().toString().equals("")){
    seven.setText(tmp);
    }
    else if(eight.getText().toString().equals("")){
    eight.setText(tmp);
    }
    else if(nine.getText().toString().equals("")){
    nine.setText(tmp);
    }
    else if(ten.getText().toString().equals("")){
    ten.setText(tmp);
    }
    else if(eleven.getText().toString().equals("")){
    eleven.setText(tmp);
    }
    else{}
    six.setText("");
    dis.setText(totalmove+"");
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
         totalmove++;
               String tmp = seven.getText().toString().trim();
       if(one.getText().toString().equals("")){
    one.setText(tmp);
    }
    else if(two.getText().toString().equals("")){
    two.setText(tmp);
    }
    else if(three.getText().toString().equals("")){
    three.setText(tmp);
    }
    else if(four.getText().toString().equals("")){
    four.setText(tmp);
    }
    else if(five.getText().toString().equals("")){
    five.setText(tmp);
    }
    else if(six.getText().toString().equals("")){
    six.setText(tmp);
    }
    else if(blank.getText().toString().equals("")){
    blank.setText(tmp);
    }
    else if(eight.getText().toString().equals("")){
    eight.setText(tmp);
    }
    else if(nine.getText().toString().equals("")){
    nine.setText(tmp);
    }
    else if(ten.getText().toString().equals("")){
    ten.setText(tmp);
    }
    else if(eleven.getText().toString().equals("")){
    eleven.setText(tmp);
    }
    else{}
    seven.setText("");
    dis.setText(totalmove+"");
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
         totalmove++;
               String tmp = eight.getText().toString().trim();
       if(one.getText().toString().equals("")){
    one.setText(tmp);
    }
    else if(two.getText().toString().equals("")){
    two.setText(tmp);
    }
    else if(three.getText().toString().equals("")){
    three.setText(tmp);
    }
    else if(four.getText().toString().equals("")){
    four.setText(tmp);
    }
    else if(five.getText().toString().equals("")){
    five.setText(tmp);
    }
    else if(six.getText().toString().equals("")){
    six.setText(tmp);
    }
    else if(seven.getText().toString().equals("")){
    seven.setText(tmp);
    }
    else if(blank.getText().toString().equals("")){
    blank.setText(tmp);
    }
    else if(nine.getText().toString().equals("")){
    nine.setText(tmp);
    }
    else if(ten.getText().toString().equals("")){
    ten.setText(tmp);
    }
    else if(eleven.getText().toString().equals("")){
    eleven.setText(tmp);
    }
    else{}
    eight.setText("");
    dis.setText(totalmove+"");
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
         totalmove++;
               String tmp = nine.getText().toString().trim();
       if(one.getText().toString().equals("")){
    one.setText(tmp);
    }
    else if(two.getText().toString().equals("")){
    two.setText(tmp);
    }
    else if(three.getText().toString().equals("")){
    three.setText(tmp);
    }
    else if(four.getText().toString().equals("")){
    four.setText(tmp);
    }
    else if(five.getText().toString().equals("")){
    five.setText(tmp);
    }
    else if(six.getText().toString().equals("")){
    six.setText(tmp);
    }
    else if(seven.getText().toString().equals("")){
    seven.setText(tmp);
    }
    else if(eight.getText().toString().equals("")){
    eight.setText(tmp);
    }
    else if(blank.getText().toString().equals("")){
    blank.setText(tmp);
    }
    else if(ten.getText().toString().equals("")){
    ten.setText(tmp);
    }
    else if(eleven.getText().toString().equals("")){
    eleven.setText(tmp);
    }
    else{}
    nine.setText("");
    dis.setText(totalmove+"");
    }//GEN-LAST:event_nineActionPerformed

    private void tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenActionPerformed
        // TODO add your handling code here:
         totalmove++;
               String tmp = ten.getText().toString().trim();
       if(one.getText().toString().equals("")){
    one.setText(tmp);
    }
    else if(two.getText().toString().equals("")){
    two.setText(tmp);
    }
    else if(three.getText().toString().equals("")){
    three.setText(tmp);
    }
    else if(four.getText().toString().equals("")){
    four.setText(tmp);
    }
    else if(five.getText().toString().equals("")){
    five.setText(tmp);
    }
    else if(six.getText().toString().equals("")){
    six.setText(tmp);
    }
    else if(seven.getText().toString().equals("")){
    seven.setText(tmp);
    }
    else if(eight.getText().toString().equals("")){
    eight.setText(tmp);
    }
    else if(nine.getText().toString().equals("")){
    nine.setText(tmp);
    }
    else if(blank.getText().toString().equals("")){
    blank.setText(tmp);
    }
    else if(eleven.getText().toString().equals("")){
    eleven.setText(tmp);
    }
    else{}
    ten.setText("");
    dis.setText(totalmove+"");
    }//GEN-LAST:event_tenActionPerformed

    private void elevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevenActionPerformed
        // TODO add your handling code here:
         totalmove++;
               String tmp = eleven.getText().toString().trim();
       if(one.getText().toString().equals("")){
    one.setText(tmp);
    }
    else if(two.getText().toString().equals("")){
    two.setText(tmp);
    }
    else if(three.getText().toString().equals("")){
    three.setText(tmp);
    }
    else if(four.getText().toString().equals("")){
    four.setText(tmp);
    }
    else if(five.getText().toString().equals("")){
    five.setText(tmp);
    }
    else if(six.getText().toString().equals("")){
    six.setText(tmp);
    }
    else if(seven.getText().toString().equals("")){
    seven.setText(tmp);
    }
    else if(eight.getText().toString().equals("")){
    eight.setText(tmp);
    }
    else if(nine.getText().toString().equals("")){
    nine.setText(tmp);
    }
    else if(ten.getText().toString().equals("")){
    ten.setText(tmp);
    }
    else if(blank.getText().toString().equals("")){
    blank.setText(tmp);
    }
    else{}
    eleven.setText("");
    dis.setText(totalmove+"");
    }//GEN-LAST:event_elevenActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        blank.setText("");
        one.setText("11");
        two.setText("9");
        three.setText("10");
        four.setText("6");
        five.setText("3"); 
        six.setText("5");
        seven.setText("1");
        eight.setText("8");
        nine.setText("2");
        ten.setText("7");
        eleven.setText("4");
        
//        blank.setText("");
//        one.setText("1");
//        two.setText("2");
//        three.setText("3");
//        four.setText("4");
//        five.setText("5"); 
//        six.setText("6");
//        seven.setText("7");
//        eight.setText("8");
//        nine.setText("9");
//        ten.setText("10");
//        eleven.setText("11");
        
       
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
        
        
       
        
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ok.setText("Game Developed By Shadman Shariar"); 
  
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blank;
    private javax.swing.JLabel dis;
    private javax.swing.JButton eight;
    private javax.swing.JButton eleven;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nine;
    private javax.swing.JLabel ok;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton ten;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    // End of variables declaration//GEN-END:variables

    private Icon getImageIcon(File file) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
